#!/bin/bash

### Script installs cert.pem to certificate trust store of applications using NSS
### (e.g. Firefox, Thunderbird, Chromium)
### Mozilla uses cert8, Chromium and Chrome use cert9

###
### CA file to install (CUSTOMIZE!)
###

# certfile="/etc/ssl/certs/the-spender.pem"
# certname="The Spender CA"

usage() {
  echo "" 1>&2;
  echo -e "\e[1mNAME\e[0m" 1>&2;
  echo "" 1>&2;
  echo -e "\tlcert - load certificate" 1>&2;
  echo "" 1>&2;
  echo -e "\e[1mSYNOSIS\e[0m" 1>&2;
  echo "" 1>&2;
  echo -e "\tlcert FILE-NAME CERT-NAME(optional)" 1>&2;
  echo "" 1>&2;
  echo -e "\e[1mDESCRIPTION\e[0m" 1>&2;
  echo -e "\tAutomatic cp and Load new cert.pem to " 1>&2;
  echo -e "\tcertificate trust store of applications using NSS" 1>&2;
  echo "" 1>&2;
  echo -e "\e[1mEXEMPLE\e[0m" 1>&2;
  echo -e "\tlcert my-cert" 1>&2;
  echo -e "\t> Do you want load /etc/ssl/certs/my-cert.pem [y/n]? y" 1>&2;
  echo -e "\t> Loaded !" 1>&2;

  exit 1;
}

if [[ "$1" != "" ]]; then
  certfile="$1"
else
  usage
fi

if [[ "$2" != "" ]]; then
  certname="$2"
else
  certname="${certfile} CA"
fi

###
### For cert8 (legacy - DBM)
###
echo "This process can take a long moment, please don't abort the task"

for certDB in $(find ~/ -name "cert8.db")
do
    echo "cert8";
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d dbm:${certdir}
done


###
### For cert9 (SQL)
###

for certDB in $(find ~/ -name "cert9.db")
do
    echo "cert9";
    certdir=$(dirname ${certDB});
    certutil -A -n "${certname}" -t "TCu,Cu,Tu" -i ${certfile} -d sql:${certdir}
done

echo "Loaded !"
