#!/bin/bash

### Script installs cert.pem to certificate trust store of applications using NSS
### (e.g. Firefox, Thunderbird, Chromium)
### Mozilla uses cert8, Chromium and Chrome use cert9

###
### CA file to install (CUSTOMIZE!)
###

IFS="."

usage() {
  echo "" 1>&2;
  echo -e "\e[1mNAME\e[0m" 1>&2;
  echo "" 1>&2;
  echo -e "\tlcert - load certificate" 1>&2;
  echo "" 1>&2;
  echo -e "\e[1mSYNOSIS\e[0m" 1>&2;
  echo "" 1>&2;
  echo -e "\tlcert FILE-NAME CERT-NAME(optional)" 1>&2;
  echo "" 1>&2;
  echo -e "\e[1mDESCRIPTION\e[0m" 1>&2;
  echo -e "\tAutomatic cp and Load new cert.pem to " 1>&2;
  echo -e "\tcertificate trust store of applications using NSS" 1>&2;
  echo "" 1>&2;
  echo -e "\e[1mEXEMPLE\e[0m" 1>&2;
  echo -e "\tlcert my-cert" 1>&2;
  echo -e "\t> Do you want load /etc/ssl/certs/my-cert.pem [y/n]? y" 1>&2;
  echo -e "\t> Loaded !" 1>&2;

  exit 1;
}

load_in_trust_store() {
  ###
  ### For cert8 (legacy - DBM)
  ###
  echo "This process can take a long moment, please don't abort the task"
  #
  # for certDB in $(find ~/ -name "cert8.db")
  # do
  #     echo "cert8";
  #     CERT_DIR=$(dirname ${certDB});
  #     certutil -A -n "${CERT_NAME}" -t "TCu,Cu,Tu" -i ${CERT_FILE} -d dbm:${CERT_DIR}
  # done
  #
  #
  # ###
  # ### For cert9 (SQL)
  # ###
  #
  # for certDB in $(find ~/ -name "cert9.db")
  # do
  #     echo "cert9";
  #     CERT_DIR=$(dirname ${certDB});
  #     certutil -A -n "${CERT_NAME}" -t "TCu,Cu,Tu" -i ${CERT_FILE} -d sql:${CERT_DIR}
  # done
  echo "Loaded !"
}

while getopts "lp:n:" arg; do
  case $arg in
    l)
      echo "only load cert"
      exit 1 || return 1
      ;;
    p)
      echo "path to cert ${OPTARG}"
      CERT_PATH=${OPTARG}
      ;;
    n)
      echo "name of cert ${OPTARG}"
      CERT_NAME=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

if [ -z "${CERT_PATH+x}" ] || [ -z "${CERT_NAME}" ]; then
  usage
else
  read -p "Do you want to copy ${CERT_PATH} into /etc/ssl/certs/${CERT_NAME} [y/n]?" -n 1 -r
  echo "" 1>&2;

  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    read -p "Do you want to load certificate in trust store of applications [y/n]?" -n 1 -r
    echo "" 1>&2;

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      [[ "$0" = "${BASH_SOURCE}" ]] && exit 1 || return 1
    fi

    CERT_FILE="/etc/ssl/certs/${CERT_NAME}"

    read -ra ADDR <<< "${CERT_NAME}"
    CERT_NAME="${ADDR[0]} CA"

    load_in_trust_store

    exit 1 || return 1
  fi

  # cp ${CERT_PATH} /etc/ssl/certs/
  echo "${CERT_PATH} copied into /etc/ssl/certs/${CERT_NAME}"

  CERT_FILE="/etc/ssl/certs/${CERT_NAME}"

  read -ra ADDR <<< "${CERT_NAME}"
  CERT_NAME="${ADDR[0]} CA"

  load_in_trust_store

  exit 1 || return 1
fi
